app_title: str = "Writer: {}"

menu_file: str = "&File"
menu_item_new: str = "New..."
menu_item_new_hint: str = "New"
menu_item_open: str = "Open..."
menu_item_open_hint: str = "Open project"
menu_item_save: str = "Save"
menu_item_save_hint: str = "Save project"
menu_item_save_as: str = "Save as..."
menu_item_save_as_hint: str = "Save project as"
menu_item_quit: str = "Quit..."
menu_item_quit_hint: str = "Save and quit"

menu_edit: str = "&Edit"
menu_item_undo: str = "Undo"
menu_item_undo_hint: str = "Undo"
menu_item_redo: str = "Redo"
menu_item_redo_hint: str = "Redo"
menu_item_bold: str = "Bold"
menu_item_bold_hint: str = "Make text bold"
menu_item_italic: str = "Italic"
menu_item_italic_hint: str = "Make text italic"
menu_item_clear: str = "Clear styles"
menu_item_clear_hint: str = "Clear styles"
menu_item_edit_words_ignored: str = "Edit ignored..."
menu_item_edit_words_ignored_hint: str = "Edit ignored"
menu_item_edit_words_names: str = "Edit names..."
menu_item_edit_words_names_hint: str = "Edit names"
menu_item_edit_words_synonyms: str = "Edit synonyms..."
menu_item_edit_words_synonyms_hint: str = "Edit synonyms"

menu_item_copy: str = "Copy"
menu_item_paste: str = "Paste"
menu_item_select_all: str = "Select all"
menu_item_add_ignored: str = "Add to ignored"
menu_item_add_name: str = "Add to names"
menu_item_del_ignored: str = "Remove from ignored"
menu_item_del_name: str = "Remove from names"
menu_item_synonym: str = "Synonym..."
menu_item_limits: str = "Set limits from"

menu_tools: str = "&Tools"
menu_item_word_list: str = "Word list"
menu_item_word_list_hint: str = "Word list"
menu_item_reset: str = "Reset limits"
menu_item_reset_hint: str = "Reset limits"

menu_about: str = "&About"
menu_item_about: str = "About..."
menu_item_about_hint: str = "About editor"

dialog_save: str = "Save file"
dialog_open: str = "Open file"
dialog_about: str = "About"
dialog_words_info: str = "Word counts"
dialog_edit: str = "{} word list"

label_coloring_box_rep: str = "Min word repetitions"
label_coloring_box_min_len: str = "Min length"
label_coloring_box_max_len: str = "Max length"
label_search_box: str = "Find"
label_search_results: str = "Matches: {}/{}"
label_word: str = "Word"
label_words: str = "Word"
label_selected: str = "✓"
label_count: str = "Count"

button_close: str = "Close"
button_cancel: str = "Cancel"
button_save: str = "Save"

status_warning: str = "Warning"
status_saved: str = "Saved"
status_not_saved: str = "Not saved"
status_ready: str = "Ready"
status_no_document: str = "No document"
status_doc_info: str = "Lines: {}, Words: {}, Chars: {}"
status_indicators: str = "Indicators: {}, free: {}"
status_ignored: str = "Ignoring: {} words"

warn_file_not_saved: str = "Save current file: {}?"
warn_errors: str = "Errors found in HTML:\n\n {}\nCan not continue\nAllowed text tags: <b>, <i>"
warn_load_last_file: str = "Load previous file: {}?"
warn_word_format_single: str = "Word list has incorrect format. One word per line is required."
warn_word_format_synonym: str = "Word list has incorrect format. Each line must have a comma separated list."
warn_selection: str = 'Selection must be a single word'

err_file_format: str = "File formatting error"
err_file_format_metadata: str = "File metadata formatting error"
err_file_permissions: str = "Can not read file"
err_file_permissions_save: str = "Permission error, can not save"

exception_resource_not_found: str = "Resource file not found"

text_about: str = "About editor:\nhttps://github.com/Athwale/hinter\nAuthor: Athwale"